add thread limit, thread number, phpunit runner specify, test files mask

diff --git a/bin/parallel-phpunit b/bin/parallel-phpunit
--- a/bin/parallel-phpunit
+++ b/bin/parallel-phpunit
@@ -2,64 +2,189 @@
 PID=$$
 ROOT="${@: -1}" # last argument
 ROOT="${ROOT%/}" # strip the last slash
-test -d "$ROOT" || ! echo "usage: parallel-phpunit [switches] <directory>" || exit 1
 ARGS="${@:1:$(($#-1))}" # remove last argument
+PHPUNIT_ARG=''
+MAX_THREAD=3
+PHPUNIT_CMD='phpunit'
+TEST_MASK="*Test.php"
 
-function test_directories {
-  find $ROOT -type d -exec `dirname $0`/directly-contains-testfile {} \; -print -prune
+
+function show_help {
+    echo "Paralleling options:"
+    echo "    --pu-cmd - custom phpunit run script, default $PHPUNIT_CMD"
+    echo "    --pu-thread - max threads, default $MAX_THREAD"
+    echo "    --pu-test-mask - tests file template, default $TEST_MASK"
+    echo "Usage: parallel-phpunit [switches] <directory>"
+    echo ""
+    exit 1
+}
+
+function set_config {
+    local pos=`expr index $1 '='`
+    local paramName=${1:0:$pos-1}
+    local paramValue=${1:$pos}
+    case $paramName in
+        --pu-thread)
+            MAX_THREAD="$paramValue"
+            ;;
+        --pu-cmd)
+            PHPUNIT_CMD="$paramValue"
+            ;;
+        --pu-test-mask)
+            TEST_MASK="$paramValue"
+            ;;
+    esac
+}
+
+
+function test_files {
+    find $ROOT -name \*$TEST_MASK
 }
 
 function replace {
-  echo "$1 " | sed "s|--$2[ ][ ]*[^ ][^ ]*|--$2 $3|"
+    echo "$1 " | sed "s|--$2[ ][ ]*[^ ][^ ]*|--$2 $3|"
+}
+
+# http://fvue.nl/wiki/Bash:_Check_if_array_element_exists
+function in_array() {
+    local hay needle=$1
+    shift
+    for hay; do
+        [[ $hay == $needle ]] && return 0
+    done
+    return 1
 }
 
 function child_processes {
-  ps -o ppid= | sed 's| *||' | grep ^${PID}$ | wc -l
+    pgrep -P ${PID} | wc -l
 }
 
 function count {
-  grep -o "$1" <<< "$progress" | wc -l | sed 's| *||'
+    grep -o "$1" <<< "$progress" | wc -l | sed 's| *||'
 }
 
 function print_summary {
-  progress=`find $ROOT -name parallel-phpunit.${PID}.log -exec cat {} \; -exec echo \; | grep "^[\.FESI][\.FESI]*$"`
-  progress=$progress`find $ROOT -name parallel-phpunit.${PID}.log -exec cat {} \; -exec echo \; | grep "^[\.FESI][\.FESI]* " | sed 's| .*||'`
-  echo "Success: `count '\.'` Fail: `count F` Error: `count E` Skip: `count S` Incomplete: `count I`"
+    progress=`find $ROOT -name parallel-phpunit.${PID}.*.log -exec cat {} \; -exec echo \; | grep "^[\.FESI][\.FESI]*$"`
+    progress=$progress`find $ROOT -name parallel-phpunit.${PID}.*.log -exec cat {} \; -exec echo \; | grep "^[\.FESI][\.FESI]* " | sed 's| .*||'`
+    echo "Success: `count '\.'` Fail: `count F` Error: `count E` Skip: `count S` Incomplete: `count I`"
 }
 
 function write_combined_junit {
-  mkdir -p `dirname $1`
-  echo "<testsuites>" > $1
-  find $ROOT -name parallel-phpunit.${PID}.junit -exec cat {} \; | grep -v "^<?xml" | grep -v testsuites >> $1
-  echo "</testsuites>" >> $1
+    mkdir -p `dirname $1`
+    echo "<testsuites>" > $1
+    find $ROOT -name parallel-phpunit.${PID}.*.junit -exec cat {} \; | grep -v "^<?xml" | grep -v testsuites >> $1
+    echo "</testsuites>" >> $1
 }
 
 function on_exit {
-  ps -o pid= -o command= | grep "parallel-phpunit-pid=${PID} " | grep -v grep | awk '{print $1}' | xargs kill -TERM 2> /dev/null
-  while [ `child_processes` -gt 1 ]
-  do
-    sleep 1
-  done
-  find $ROOT -name parallel-phpunit.${PID}* -delete
+    pkill -TERM -P ${PID} &
+    while [ `child_processes` -gt 1 ]
+    do
+        sleep 1
+    done
+    find $ROOT -name parallel-phpunit.${PID}* -delete
 }
 
 trap "on_exit" EXIT
 
+
+function refresh_threads {
+    declare -a child_list=("${!1}")
+    local active=()
+    active=(`pgrep -P ${PID}`)
+    local i=0
+    while [ $i -lt $MAX_THREAD ]
+    do
+        local pid=${child_list[$i]}
+        in_array $pid ${active[@]}
+        if [ ! $? -eq 0 ];then
+            child_list[$i]=0
+        fi
+        i=`expr $i + 1`
+    done
+    echo ${child_list[@]}
+}
+
+
+function get_free_thread {
+    declare -a child_list=("${!1}")
+    local i=0
+    while [ $i -lt $MAX_THREAD ]
+    do
+        if [ ${child_list[$i]} -eq 0 ];then
+            echo $i
+            return
+        fi
+    i=`expr $i + 1`
+    done
+    echo '-1'
+}
+
+
+
 echo "Running parallel wrapper for phpunit"
-junit_file=`echo "$ARGS" | grep "\-\-log-junit " | sed 's|.*--log-junit [ ]*||' | sed 's| .*||'`
-for dir in `test_directories`
+
+#check parameters
+
+if [ ! -d "$ROOT" ];then
+    show_help
+    exit 1
+fi
+
+#extract extended options
+for param in $ARGS
 do
-  log=$dir/parallel-phpunit.${PID}.log
-  args="`replace "$ARGS" log-junit $dir/parallel-phpunit.${PID}.junit` $dir"
-  echo "Starting command: phpunit $args"
-  ((phpunit -d parallel-phpunit-pid=${PID} $args || touch $dir/parallel-phpunit.${PID}.fail) &> $log; echo "Command ended: phpunit $args"; grep -v "parallel-phpunit-pid=" $log) &
+    if [ ${param:0:4} = '--pu' ];then
+        set_config "$param"
+    else
+        PHPUNIT_ARG="$PHPUNIT_ARG $param"
+    fi
 done
 
-while [ `child_processes` -gt 1 ] # report progress when some phpunit execution is still running
+
+# init vars
+threads=()
+i=0
+while [ $i -lt $MAX_THREAD ]
 do
-  sleep 2
-  print_summary
+    threads[$i]=0
+    i=`expr $i + 1`
+done
+
+junit_file=`echo "$PHPUNIT_ARG" | grep "\-\-log-junit " | sed 's|.*--log-junit [ ]*||' | sed 's| .*||'`
+
+#execute tests
+i=0
+for filename in `test_files`
+do
+    #check active process
+    while [ `child_processes` -gt $MAX_THREAD ]
+    do
+        sleep 1
+    done
+    #extract dir
+    dir="$filename"
+    if [ -f "$filename" ]; then
+        dir=`dirname $filename`
+    fi
+    i=`expr $i + 1`
+    #get free thread number
+    threads=( $(refresh_threads threads[@]) )
+    thread_id=`get_free_thread threads[@]`
+    #execute
+    log=$dir/parallel-phpunit.${PID}.${i}.log
+    args="`replace "$PHPUNIT_ARG" log-junit $dir/parallel-phpunit.${PID}.${i}.junit` $filename"
+    echo "Starting command: phpunit $args thread_id $thread_id"
+    (($PHPUNIT_CMD -d parallel-phpunit-thread=${thread_id} $args || touch $dir/parallel-phpunit.${PID}.${i}.fail) &> $log; echo "Command ended: phpunit $args"; grep -v "parallel-phpunit-pid=" $log) &
+    threads[$thread_id]=$!
+done
+
+#report progress when some phpunit execution is still running
+while [ `child_processes` -gt 1 ]
+do
+    sleep 2
+    print_summary
 done
 
 test -z "$junit_file" || write_combined_junit $junit_file
-test -z "`find $ROOT -name parallel-phpunit.${PID}.fail`"
+test -z "`find $ROOT -name parallel-phpunit.${PID}.*.fail`"
